FROM node:21-alpine3.18 as build
WORKDIR /app
ADD *.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:21-alpine3.18
WORKDIR /app
COPY --from=build /app/dist ./dist
ADD *.json ./
RUN npm install --omit=dev
COPY . .
RUN rm -rf ./src
# EXPOSE 4001
CMD [ "npm", "run", "start:prod" ]