version: '4.27.2'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nestjs-prod
    restart: unless-stopped
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    environment:
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL}
    working_dir: /app

  redis:
    container_name: redis-db
    image: redis
    environment:
      - REDIS_PORT=6379
    ports:
      - 6379:6379
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - redis:/data
