version: '4.27.2'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      PORT: 8000
      DATABASE_URL: ${DATABASE_URL}
    working_dir: /app
    links:
      - redis
    networks:
      - webnet
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - webnet
    # environment:
    #   - REDIS_PORT=6379

volumes:
  redis:

networks:
  webnet:
